
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package publicadores;

import java.util.logging.Logger;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-11-10T11:07:44.325-03:00
 * Generated source version: 4.0.3
 *
 */

@jakarta.jws.WebService(
                      serviceName = "ControladorPublishService",
                      portName = "ControladorPublishPort",
                      targetNamespace = "http://publicadores/",
                      wsdlLocation = "http://127.0.0.1:1942/controlador?wsdl",
                      endpointInterface = "publicadores.ControladorPublish")

public class ControladorPublishPortImpl implements ControladorPublish {

    private static final Logger LOG = Logger.getLogger(ControladorPublishPortImpl.class.getName());

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#modificarUsuarioWeb(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, publicadores.LocalDate arg3, java.lang.String arg4)*
     */
    public boolean modificarUsuarioWeb(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, LocalDate arg3, java.lang.String arg4) {
        LOG.info("Executing operation modificarUsuarioWeb");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#existenElementos(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3)*
     */
    public boolean existenElementos(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3) {
        LOG.info("Executing operation existenElementos");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#getSociosByClase(publicadores.Clase arg0)*
     */
    public publicadores.ArrayList getSociosByClase(Clase arg0) {
        LOG.info("Executing operation getSociosByClase");
        System.out.println(arg0);
        try {
            publicadores.ArrayList _return = new publicadores.ArrayList();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#getClasesByUser(java.lang.String arg0)*
     */
    public publicadores.ArrayList getClasesByUser(java.lang.String arg0) {
        LOG.info("Executing operation getClasesByUser");
        System.out.println(arg0);
        try {
            publicadores.ArrayList _return = new publicadores.ArrayList();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#getClasesByActividad(java.lang.String arg0)*
     */
    public publicadores.ArrayList getClasesByActividad(java.lang.String arg0) {
        LOG.info("Executing operation getClasesByActividad");
        System.out.println(arg0);
        try {
            publicadores.ArrayList _return = new publicadores.ArrayList();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#validateDataWeb(java.lang.String arg0, java.lang.String arg1)*
     */
    public boolean validateDataWeb(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation validateDataWeb");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#obtenerActividadPorNombre(java.lang.String arg0)*
     */
    public publicadores.ActividadDeportiva obtenerActividadPorNombre(java.lang.String arg0) {
        LOG.info("Executing operation obtenerActividadPorNombre");
        System.out.println(arg0);
        try {
            publicadores.ActividadDeportiva _return = new publicadores.ActividadDeportiva();
            _return.setCosto(0.9883738f);
            _return.setDescripcion("Descripcion-804198453");
            _return.setDuracion(-407782331);
            publicadores.LocalDate _returnFechaReg = new publicadores.LocalDate();
            _return.setFechaReg(_returnFechaReg);
            _return.setImg("Img-1393550605");
            _return.setNombre("Nombre2146449683");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#obtenerClasesPorActividad(publicadores.ActividadDeportiva arg0)*
     */
    public publicadores.ArrayList obtenerClasesPorActividad(ActividadDeportiva arg0) {
        LOG.info("Executing operation obtenerClasesPorActividad");
        System.out.println(arg0);
        try {
            publicadores.ArrayList _return = new publicadores.ArrayList();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#obtenerRankingDeActividades()*
     */
    public publicadores.ArrayList obtenerRankingDeActividades() {
        LOG.info("Executing operation obtenerRankingDeActividades");
        try {
            publicadores.ArrayList _return = new publicadores.ArrayList();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#addClase(java.lang.String arg0, publicadores.LocalDate arg1, publicadores.LocalTime arg2, java.lang.String arg3, publicadores.LocalDate arg4, java.lang.String arg5, java.lang.String arg6, java.lang.String arg7)*
     */
    public void addClase(java.lang.String arg0, LocalDate arg1, LocalTime arg2, java.lang.String arg3, LocalDate arg4, java.lang.String arg5, java.lang.String arg6, java.lang.String arg7) {
        LOG.info("Executing operation addClase");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        System.out.println(arg6);
        System.out.println(arg7);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#getClaseByNombre(java.lang.String arg0)*
     */
    public publicadores.Clase getClaseByNombre(java.lang.String arg0) {
        LOG.info("Executing operation getClaseByNombre");
        System.out.println(arg0);
        try {
            publicadores.Clase _return = new publicadores.Clase();
            publicadores.LocalDate _returnFecha = new publicadores.LocalDate();
            _return.setFecha(_returnFecha);
            publicadores.LocalDate _returnFechaReg = new publicadores.LocalDate();
            _return.setFechaReg(_returnFechaReg);
            publicadores.LocalTime _returnHora = new publicadores.LocalTime();
            _return.setHora(_returnHora);
            _return.setImg("Img-2100797392");
            _return.setNombre("Nombre1664232783");
            publicadores.Profesor _returnProfesor = new publicadores.Profesor();
            _returnProfesor.setApellido("Apellido-1479146992");
            _returnProfesor.setContrasena("Contrasena-885612515");
            _returnProfesor.setEmail("Email-1693934972");
            publicadores.LocalDate _returnProfesorFechaNac = new publicadores.LocalDate();
            _returnProfesor.setFechaNac(_returnProfesorFechaNac);
            _returnProfesor.setImg("Img-446855132");
            _returnProfesor.setNickname("Nickname-1493523060");
            _returnProfesor.setNombre("Nombre-1380198699");
            _returnProfesor.setBiografia("Biografia-965515198");
            _returnProfesor.setDescripcion("Descripcion-514812176");
            publicadores.InstitucionDeportiva _returnProfesorInstitucion = new publicadores.InstitucionDeportiva();
            java.util.List<publicadores.ActividadDeportiva> _returnProfesorInstitucionActividades = new java.util.ArrayList<publicadores.ActividadDeportiva>();
            _returnProfesorInstitucion.getActividades().addAll(_returnProfesorInstitucionActividades);
            _returnProfesorInstitucion.setDescripcion("Descripcion-1437516362");
            _returnProfesorInstitucion.setNombre("Nombre409728942");
            _returnProfesorInstitucion.setUrl("Url111115568");
            _returnProfesor.setInstitucion(_returnProfesorInstitucion);
            _returnProfesor.setSitioWeb("SitioWeb-860998917");
            _return.setProfesor(_returnProfesor);
            java.util.List<publicadores.Registro> _returnRegistros = new java.util.ArrayList<publicadores.Registro>();
            publicadores.Registro _returnRegistrosVal1 = new publicadores.Registro();
            publicadores.Clase _returnRegistrosVal1Clase = new publicadores.Clase();
            publicadores.LocalDate _returnRegistrosVal1ClaseFecha = new publicadores.LocalDate();
            _returnRegistrosVal1Clase.setFecha(_returnRegistrosVal1ClaseFecha);
            publicadores.LocalDate _returnRegistrosVal1ClaseFechaReg = new publicadores.LocalDate();
            _returnRegistrosVal1Clase.setFechaReg(_returnRegistrosVal1ClaseFechaReg);
            publicadores.LocalTime _returnRegistrosVal1ClaseHora = new publicadores.LocalTime();
            _returnRegistrosVal1Clase.setHora(_returnRegistrosVal1ClaseHora);
            _returnRegistrosVal1Clase.setImg("Img-1024673325");
            _returnRegistrosVal1Clase.setNombre("Nombre2109633692");
            publicadores.Profesor _returnRegistrosVal1ClaseProfesor = new publicadores.Profesor();
            _returnRegistrosVal1ClaseProfesor.setApellido("Apellido-119332416");
            _returnRegistrosVal1ClaseProfesor.setContrasena("Contrasena-110948034");
            _returnRegistrosVal1ClaseProfesor.setEmail("Email-1516580065");
            publicadores.LocalDate _returnRegistrosVal1ClaseProfesorFechaNac = new publicadores.LocalDate();
            _returnRegistrosVal1ClaseProfesor.setFechaNac(_returnRegistrosVal1ClaseProfesorFechaNac);
            _returnRegistrosVal1ClaseProfesor.setImg("Img-1870477374");
            _returnRegistrosVal1ClaseProfesor.setNickname("Nickname-131258439");
            _returnRegistrosVal1ClaseProfesor.setNombre("Nombre-1442757575");
            _returnRegistrosVal1ClaseProfesor.setBiografia("Biografia334416913");
            _returnRegistrosVal1ClaseProfesor.setDescripcion("Descripcion-268764304");
            publicadores.InstitucionDeportiva _returnRegistrosVal1ClaseProfesorInstitucion = new publicadores.InstitucionDeportiva();
            java.util.List<publicadores.ActividadDeportiva> _returnRegistrosVal1ClaseProfesorInstitucionActividades = new java.util.ArrayList<publicadores.ActividadDeportiva>();
            _returnRegistrosVal1ClaseProfesorInstitucion.getActividades().addAll(_returnRegistrosVal1ClaseProfesorInstitucionActividades);
            _returnRegistrosVal1ClaseProfesorInstitucion.setDescripcion("Descripcion660997398");
            _returnRegistrosVal1ClaseProfesorInstitucion.setNombre("Nombre1030850307");
            _returnRegistrosVal1ClaseProfesorInstitucion.setUrl("Url1319264227");
            _returnRegistrosVal1ClaseProfesor.setInstitucion(_returnRegistrosVal1ClaseProfesorInstitucion);
            _returnRegistrosVal1ClaseProfesor.setSitioWeb("SitioWeb939670860");
            _returnRegistrosVal1Clase.setProfesor(_returnRegistrosVal1ClaseProfesor);
            java.util.List<publicadores.Registro> _returnRegistrosVal1ClaseRegistros = new java.util.ArrayList<publicadores.Registro>();
            _returnRegistrosVal1Clase.getRegistros().addAll(_returnRegistrosVal1ClaseRegistros);
            _returnRegistrosVal1Clase.setUrl("Url-972211922");
            _returnRegistrosVal1.setClase(_returnRegistrosVal1Clase);
            publicadores.LocalDate _returnRegistrosVal1FechaReg = new publicadores.LocalDate();
            _returnRegistrosVal1.setFechaReg(_returnRegistrosVal1FechaReg);
            publicadores.Socio _returnRegistrosVal1Socio = new publicadores.Socio();
            _returnRegistrosVal1Socio.setApellido("Apellido335914402");
            _returnRegistrosVal1Socio.setContrasena("Contrasena764913233");
            _returnRegistrosVal1Socio.setEmail("Email-584257330");
            publicadores.LocalDate _returnRegistrosVal1SocioFechaNac = new publicadores.LocalDate();
            _returnRegistrosVal1Socio.setFechaNac(_returnRegistrosVal1SocioFechaNac);
            _returnRegistrosVal1Socio.setImg("Img1432707092");
            _returnRegistrosVal1Socio.setNickname("Nickname-1797744996");
            _returnRegistrosVal1Socio.setNombre("Nombre-1389432928");
            java.util.List<publicadores.Registro> _returnRegistrosVal1SocioClasesRegistradas = new java.util.ArrayList<publicadores.Registro>();
            _returnRegistrosVal1Socio.getClasesRegistradas().addAll(_returnRegistrosVal1SocioClasesRegistradas);
            _returnRegistrosVal1.setSocio(_returnRegistrosVal1Socio);
            _returnRegistros.add(_returnRegistrosVal1);
            _return.getRegistros().addAll(_returnRegistros);
            _return.setUrl("Url-911018767");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#crearRegistro(publicadores.Socio arg0, publicadores.Clase arg1)*
     */
    public boolean crearRegistro(Socio arg0, Clase arg1) {
        LOG.info("Executing operation crearRegistro");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#obtenerClasePorNombre(java.lang.String arg0)*
     */
    public publicadores.Clase obtenerClasePorNombre(java.lang.String arg0) {
        LOG.info("Executing operation obtenerClasePorNombre");
        System.out.println(arg0);
        try {
            publicadores.Clase _return = new publicadores.Clase();
            publicadores.LocalDate _returnFecha = new publicadores.LocalDate();
            _return.setFecha(_returnFecha);
            publicadores.LocalDate _returnFechaReg = new publicadores.LocalDate();
            _return.setFechaReg(_returnFechaReg);
            publicadores.LocalTime _returnHora = new publicadores.LocalTime();
            _return.setHora(_returnHora);
            _return.setImg("Img1679694286");
            _return.setNombre("Nombre-632300319");
            publicadores.Profesor _returnProfesor = new publicadores.Profesor();
            _returnProfesor.setApellido("Apellido1607209255");
            _returnProfesor.setContrasena("Contrasena-574808466");
            _returnProfesor.setEmail("Email1657598075");
            publicadores.LocalDate _returnProfesorFechaNac = new publicadores.LocalDate();
            _returnProfesor.setFechaNac(_returnProfesorFechaNac);
            _returnProfesor.setImg("Img-1498072970");
            _returnProfesor.setNickname("Nickname338804108");
            _returnProfesor.setNombre("Nombre-1623702586");
            _returnProfesor.setBiografia("Biografia-1020525913");
            _returnProfesor.setDescripcion("Descripcion-1174449451");
            publicadores.InstitucionDeportiva _returnProfesorInstitucion = new publicadores.InstitucionDeportiva();
            java.util.List<publicadores.ActividadDeportiva> _returnProfesorInstitucionActividades = new java.util.ArrayList<publicadores.ActividadDeportiva>();
            _returnProfesorInstitucion.getActividades().addAll(_returnProfesorInstitucionActividades);
            _returnProfesorInstitucion.setDescripcion("Descripcion1861794398");
            _returnProfesorInstitucion.setNombre("Nombre-15457732");
            _returnProfesorInstitucion.setUrl("Url1031538086");
            _returnProfesor.setInstitucion(_returnProfesorInstitucion);
            _returnProfesor.setSitioWeb("SitioWeb839444364");
            _return.setProfesor(_returnProfesor);
            java.util.List<publicadores.Registro> _returnRegistros = new java.util.ArrayList<publicadores.Registro>();
            publicadores.Registro _returnRegistrosVal1 = new publicadores.Registro();
            publicadores.Clase _returnRegistrosVal1Clase = new publicadores.Clase();
            publicadores.LocalDate _returnRegistrosVal1ClaseFecha = new publicadores.LocalDate();
            _returnRegistrosVal1Clase.setFecha(_returnRegistrosVal1ClaseFecha);
            publicadores.LocalDate _returnRegistrosVal1ClaseFechaReg = new publicadores.LocalDate();
            _returnRegistrosVal1Clase.setFechaReg(_returnRegistrosVal1ClaseFechaReg);
            publicadores.LocalTime _returnRegistrosVal1ClaseHora = new publicadores.LocalTime();
            _returnRegistrosVal1Clase.setHora(_returnRegistrosVal1ClaseHora);
            _returnRegistrosVal1Clase.setImg("Img-853005651");
            _returnRegistrosVal1Clase.setNombre("Nombre2003612473");
            publicadores.Profesor _returnRegistrosVal1ClaseProfesor = new publicadores.Profesor();
            _returnRegistrosVal1ClaseProfesor.setApellido("Apellido-243501073");
            _returnRegistrosVal1ClaseProfesor.setContrasena("Contrasena574017156");
            _returnRegistrosVal1ClaseProfesor.setEmail("Email-1852103090");
            publicadores.LocalDate _returnRegistrosVal1ClaseProfesorFechaNac = new publicadores.LocalDate();
            _returnRegistrosVal1ClaseProfesor.setFechaNac(_returnRegistrosVal1ClaseProfesorFechaNac);
            _returnRegistrosVal1ClaseProfesor.setImg("Img481766523");
            _returnRegistrosVal1ClaseProfesor.setNickname("Nickname-1910241739");
            _returnRegistrosVal1ClaseProfesor.setNombre("Nombre-1371865719");
            _returnRegistrosVal1ClaseProfesor.setBiografia("Biografia-1693124843");
            _returnRegistrosVal1ClaseProfesor.setDescripcion("Descripcion-1756575944");
            publicadores.InstitucionDeportiva _returnRegistrosVal1ClaseProfesorInstitucion = new publicadores.InstitucionDeportiva();
            java.util.List<publicadores.ActividadDeportiva> _returnRegistrosVal1ClaseProfesorInstitucionActividades = new java.util.ArrayList<publicadores.ActividadDeportiva>();
            _returnRegistrosVal1ClaseProfesorInstitucion.getActividades().addAll(_returnRegistrosVal1ClaseProfesorInstitucionActividades);
            _returnRegistrosVal1ClaseProfesorInstitucion.setDescripcion("Descripcion231845304");
            _returnRegistrosVal1ClaseProfesorInstitucion.setNombre("Nombre-850944503");
            _returnRegistrosVal1ClaseProfesorInstitucion.setUrl("Url1329558850");
            _returnRegistrosVal1ClaseProfesor.setInstitucion(_returnRegistrosVal1ClaseProfesorInstitucion);
            _returnRegistrosVal1ClaseProfesor.setSitioWeb("SitioWeb733500809");
            _returnRegistrosVal1Clase.setProfesor(_returnRegistrosVal1ClaseProfesor);
            java.util.List<publicadores.Registro> _returnRegistrosVal1ClaseRegistros = new java.util.ArrayList<publicadores.Registro>();
            _returnRegistrosVal1Clase.getRegistros().addAll(_returnRegistrosVal1ClaseRegistros);
            _returnRegistrosVal1Clase.setUrl("Url1673342935");
            _returnRegistrosVal1.setClase(_returnRegistrosVal1Clase);
            publicadores.LocalDate _returnRegistrosVal1FechaReg = new publicadores.LocalDate();
            _returnRegistrosVal1.setFechaReg(_returnRegistrosVal1FechaReg);
            publicadores.Socio _returnRegistrosVal1Socio = new publicadores.Socio();
            _returnRegistrosVal1Socio.setApellido("Apellido255277851");
            _returnRegistrosVal1Socio.setContrasena("Contrasena-1982974149");
            _returnRegistrosVal1Socio.setEmail("Email998066694");
            publicadores.LocalDate _returnRegistrosVal1SocioFechaNac = new publicadores.LocalDate();
            _returnRegistrosVal1Socio.setFechaNac(_returnRegistrosVal1SocioFechaNac);
            _returnRegistrosVal1Socio.setImg("Img1690479338");
            _returnRegistrosVal1Socio.setNickname("Nickname1643858883");
            _returnRegistrosVal1Socio.setNombre("Nombre1803061371");
            java.util.List<publicadores.Registro> _returnRegistrosVal1SocioClasesRegistradas = new java.util.ArrayList<publicadores.Registro>();
            _returnRegistrosVal1Socio.getClasesRegistradas().addAll(_returnRegistrosVal1SocioClasesRegistradas);
            _returnRegistrosVal1.setSocio(_returnRegistrosVal1Socio);
            _returnRegistros.add(_returnRegistrosVal1);
            _return.getRegistros().addAll(_returnRegistros);
            _return.setUrl("Url978654637");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#iniciarSesion(java.lang.String arg0, java.lang.String arg1)*
     */
    public publicadores.Sesion iniciarSesion(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation iniciarSesion");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            publicadores.Sesion _return = new publicadores.Sesion();
            _return.setApellido("Apellido-1693553586");
            _return.setEmail("Email-1829593740");
            _return.setFechaNacimiento("FechaNacimiento-1188602934");
            _return.setNickname("Nickname-599130105");
            _return.setNombre("Nombre2129350592");
            _return.setProfileImageBase64("ProfileImageBase64-1579326763");
            _return.setUserType("UserType131312814");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#getInstitucionesByName(java.lang.String arg0)*
     */
    public publicadores.InstitucionDeportiva getInstitucionesByName(java.lang.String arg0) {
        LOG.info("Executing operation getInstitucionesByName");
        System.out.println(arg0);
        try {
            publicadores.InstitucionDeportiva _return = new publicadores.InstitucionDeportiva();
            java.util.List<publicadores.ActividadDeportiva> _returnActividades = new java.util.ArrayList<publicadores.ActividadDeportiva>();
            publicadores.ActividadDeportiva _returnActividadesVal1 = new publicadores.ActividadDeportiva();
            _returnActividadesVal1.setCosto(0.9917734f);
            _returnActividadesVal1.setDescripcion("Descripcion1078411246");
            _returnActividadesVal1.setDuracion(2050812615);
            publicadores.LocalDate _returnActividadesVal1FechaReg = new publicadores.LocalDate();
            _returnActividadesVal1.setFechaReg(_returnActividadesVal1FechaReg);
            _returnActividadesVal1.setImg("Img-664468447");
            _returnActividadesVal1.setNombre("Nombre-619362233");
            _returnActividades.add(_returnActividadesVal1);
            _return.getActividades().addAll(_returnActividades);
            _return.setDescripcion("Descripcion967224395");
            _return.setNombre("Nombre407454631");
            _return.setUrl("Url2141656195");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#getActividadesByProfe(java.lang.String arg0)*
     */
    public publicadores.ArrayList getActividadesByProfe(java.lang.String arg0) {
        LOG.info("Executing operation getActividadesByProfe");
        System.out.println(arg0);
        try {
            publicadores.ArrayList _return = new publicadores.ArrayList();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#addRegistroDictadoWeb(java.lang.String arg0, java.lang.String arg1, publicadores.LocalDate arg2)*
     */
    public boolean addRegistroDictadoWeb(java.lang.String arg0, java.lang.String arg1, LocalDate arg2) {
        LOG.info("Executing operation addRegistroDictadoWeb");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#obtenerRankingDeClases()*
     */
    public publicadores.ArrayList obtenerRankingDeClases() {
        LOG.info("Executing operation obtenerRankingDeClases");
        try {
            publicadores.ArrayList _return = new publicadores.ArrayList();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#getInstituciones()*
     */
    public publicadores.ArrayList getInstituciones() {
        LOG.info("Executing operation getInstituciones");
        try {
            publicadores.ArrayList _return = new publicadores.ArrayList();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#getSocio(java.lang.String arg0)*
     */
    public publicadores.Socio getSocio(java.lang.String arg0) {
        LOG.info("Executing operation getSocio");
        System.out.println(arg0);
        try {
            publicadores.Socio _return = new publicadores.Socio();
            _return.setApellido("Apellido-1216804830");
            _return.setContrasena("Contrasena-796438832");
            _return.setEmail("Email-328687407");
            publicadores.LocalDate _returnFechaNac = new publicadores.LocalDate();
            _return.setFechaNac(_returnFechaNac);
            _return.setImg("Img-454341389");
            _return.setNickname("Nickname-1286756626");
            _return.setNombre("Nombre2024671331");
            java.util.List<publicadores.Registro> _returnClasesRegistradas = new java.util.ArrayList<publicadores.Registro>();
            publicadores.Registro _returnClasesRegistradasVal1 = new publicadores.Registro();
            publicadores.Clase _returnClasesRegistradasVal1Clase = new publicadores.Clase();
            publicadores.LocalDate _returnClasesRegistradasVal1ClaseFecha = new publicadores.LocalDate();
            _returnClasesRegistradasVal1Clase.setFecha(_returnClasesRegistradasVal1ClaseFecha);
            publicadores.LocalDate _returnClasesRegistradasVal1ClaseFechaReg = new publicadores.LocalDate();
            _returnClasesRegistradasVal1Clase.setFechaReg(_returnClasesRegistradasVal1ClaseFechaReg);
            publicadores.LocalTime _returnClasesRegistradasVal1ClaseHora = new publicadores.LocalTime();
            _returnClasesRegistradasVal1Clase.setHora(_returnClasesRegistradasVal1ClaseHora);
            _returnClasesRegistradasVal1Clase.setImg("Img809837335");
            _returnClasesRegistradasVal1Clase.setNombre("Nombre-530537449");
            publicadores.Profesor _returnClasesRegistradasVal1ClaseProfesor = new publicadores.Profesor();
            _returnClasesRegistradasVal1ClaseProfesor.setApellido("Apellido-896955928");
            _returnClasesRegistradasVal1ClaseProfesor.setContrasena("Contrasena-1506670775");
            _returnClasesRegistradasVal1ClaseProfesor.setEmail("Email-239213021");
            publicadores.LocalDate _returnClasesRegistradasVal1ClaseProfesorFechaNac = new publicadores.LocalDate();
            _returnClasesRegistradasVal1ClaseProfesor.setFechaNac(_returnClasesRegistradasVal1ClaseProfesorFechaNac);
            _returnClasesRegistradasVal1ClaseProfesor.setImg("Img-1793408035");
            _returnClasesRegistradasVal1ClaseProfesor.setNickname("Nickname959705824");
            _returnClasesRegistradasVal1ClaseProfesor.setNombre("Nombre1991932281");
            _returnClasesRegistradasVal1ClaseProfesor.setBiografia("Biografia1734248059");
            _returnClasesRegistradasVal1ClaseProfesor.setDescripcion("Descripcion-465528186");
            publicadores.InstitucionDeportiva _returnClasesRegistradasVal1ClaseProfesorInstitucion = new publicadores.InstitucionDeportiva();
            java.util.List<publicadores.ActividadDeportiva> _returnClasesRegistradasVal1ClaseProfesorInstitucionActividades = new java.util.ArrayList<publicadores.ActividadDeportiva>();
            _returnClasesRegistradasVal1ClaseProfesorInstitucion.getActividades().addAll(_returnClasesRegistradasVal1ClaseProfesorInstitucionActividades);
            _returnClasesRegistradasVal1ClaseProfesorInstitucion.setDescripcion("Descripcion880332880");
            _returnClasesRegistradasVal1ClaseProfesorInstitucion.setNombre("Nombre1093869686");
            _returnClasesRegistradasVal1ClaseProfesorInstitucion.setUrl("Url653528720");
            _returnClasesRegistradasVal1ClaseProfesor.setInstitucion(_returnClasesRegistradasVal1ClaseProfesorInstitucion);
            _returnClasesRegistradasVal1ClaseProfesor.setSitioWeb("SitioWeb-1661649156");
            _returnClasesRegistradasVal1Clase.setProfesor(_returnClasesRegistradasVal1ClaseProfesor);
            java.util.List<publicadores.Registro> _returnClasesRegistradasVal1ClaseRegistros = new java.util.ArrayList<publicadores.Registro>();
            _returnClasesRegistradasVal1Clase.getRegistros().addAll(_returnClasesRegistradasVal1ClaseRegistros);
            _returnClasesRegistradasVal1Clase.setUrl("Url853366445");
            _returnClasesRegistradasVal1.setClase(_returnClasesRegistradasVal1Clase);
            publicadores.LocalDate _returnClasesRegistradasVal1FechaReg = new publicadores.LocalDate();
            _returnClasesRegistradasVal1.setFechaReg(_returnClasesRegistradasVal1FechaReg);
            publicadores.Socio _returnClasesRegistradasVal1Socio = new publicadores.Socio();
            _returnClasesRegistradasVal1Socio.setApellido("Apellido-949808613");
            _returnClasesRegistradasVal1Socio.setContrasena("Contrasena1620910642");
            _returnClasesRegistradasVal1Socio.setEmail("Email-801855175");
            publicadores.LocalDate _returnClasesRegistradasVal1SocioFechaNac = new publicadores.LocalDate();
            _returnClasesRegistradasVal1Socio.setFechaNac(_returnClasesRegistradasVal1SocioFechaNac);
            _returnClasesRegistradasVal1Socio.setImg("Img-1558947072");
            _returnClasesRegistradasVal1Socio.setNickname("Nickname-1339539046");
            _returnClasesRegistradasVal1Socio.setNombre("Nombre787279174");
            java.util.List<publicadores.Registro> _returnClasesRegistradasVal1SocioClasesRegistradas = new java.util.ArrayList<publicadores.Registro>();
            _returnClasesRegistradasVal1Socio.getClasesRegistradas().addAll(_returnClasesRegistradasVal1SocioClasesRegistradas);
            _returnClasesRegistradasVal1.setSocio(_returnClasesRegistradasVal1Socio);
            _returnClasesRegistradas.add(_returnClasesRegistradasVal1);
            _return.getClasesRegistradas().addAll(_returnClasesRegistradas);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPublish#eliminarRegistroDeClase(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3)*
     */
    public boolean eliminarRegistroDeClase(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3) {
        LOG.info("Executing operation eliminarRegistroDeClase");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
