package publicadores;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-11-10T11:07:44.342-03:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "ControladorPublishService",
                  wsdlLocation = "http://127.0.0.1:1942/controlador?wsdl",
                  targetNamespace = "http://publicadores/")
public class ControladorPublishService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://publicadores/", "ControladorPublishService");
    public final static QName ControladorPublishPort = new QName("http://publicadores/", "ControladorPublishPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:1942/controlador?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ControladorPublishService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:1942/controlador?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ControladorPublishService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ControladorPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControladorPublishService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ControladorPublishService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ControladorPublishService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ControladorPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ControladorPublish
     */
    @WebEndpoint(name = "ControladorPublishPort")
    public ControladorPublish getControladorPublishPort() {
        return super.getPort(ControladorPublishPort, ControladorPublish.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControladorPublish
     */
    @WebEndpoint(name = "ControladorPublishPort")
    public ControladorPublish getControladorPublishPort(WebServiceFeature... features) {
        return super.getPort(ControladorPublishPort, ControladorPublish.class, features);
    }

}
