
package publicadores;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-11-10T11:07:44.279-03:00
 * Generated source version: 4.0.3
 *
 */
public final class ControladorPublish_ControladorPublishPort_Client {

    private static final QName SERVICE_NAME = new QName("http://publicadores/", "ControladorPublishService");

    private ControladorPublish_ControladorPublishPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ControladorPublishService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ControladorPublishService ss = new ControladorPublishService(wsdlURL, SERVICE_NAME);
        ControladorPublish port = ss.getControladorPublishPort();

        {
        System.out.println("Invoking modificarUsuarioWeb...");
        java.lang.String _modificarUsuarioWeb_arg0 = "_modificarUsuarioWeb_arg0-148066890";
        java.lang.String _modificarUsuarioWeb_arg1 = "_modificarUsuarioWeb_arg1-1467106359";
        java.lang.String _modificarUsuarioWeb_arg2 = "_modificarUsuarioWeb_arg2-970911029";
        publicadores.LocalDate _modificarUsuarioWeb_arg3 = new publicadores.LocalDate();
        java.lang.String _modificarUsuarioWeb_arg4 = "_modificarUsuarioWeb_arg4887005805";
        boolean _modificarUsuarioWeb__return = port.modificarUsuarioWeb(_modificarUsuarioWeb_arg0, _modificarUsuarioWeb_arg1, _modificarUsuarioWeb_arg2, _modificarUsuarioWeb_arg3, _modificarUsuarioWeb_arg4);
        System.out.println("modificarUsuarioWeb.result=" + _modificarUsuarioWeb__return);


        }
        {
        System.out.println("Invoking existenElementos...");
        java.lang.String _existenElementos_arg0 = "_existenElementos_arg0-706481613";
        java.lang.String _existenElementos_arg1 = "_existenElementos_arg1-1128846515";
        java.lang.String _existenElementos_arg2 = "_existenElementos_arg2816041783";
        java.lang.String _existenElementos_arg3 = "_existenElementos_arg3452529692";
        boolean _existenElementos__return = port.existenElementos(_existenElementos_arg0, _existenElementos_arg1, _existenElementos_arg2, _existenElementos_arg3);
        System.out.println("existenElementos.result=" + _existenElementos__return);


        }
        {
        System.out.println("Invoking getSociosByClase...");
        publicadores.Clase _getSociosByClase_arg0 = new publicadores.Clase();
        publicadores.LocalDate _getSociosByClase_arg0Fecha = new publicadores.LocalDate();
        _getSociosByClase_arg0.setFecha(_getSociosByClase_arg0Fecha);
        publicadores.LocalDate _getSociosByClase_arg0FechaReg = new publicadores.LocalDate();
        _getSociosByClase_arg0.setFechaReg(_getSociosByClase_arg0FechaReg);
        publicadores.LocalTime _getSociosByClase_arg0Hora = new publicadores.LocalTime();
        _getSociosByClase_arg0.setHora(_getSociosByClase_arg0Hora);
        _getSociosByClase_arg0.setImg("Img-1973223604");
        _getSociosByClase_arg0.setNombre("Nombre1545179071");
        publicadores.Profesor _getSociosByClase_arg0Profesor = new publicadores.Profesor();
        _getSociosByClase_arg0Profesor.setApellido("Apellido1772772401");
        _getSociosByClase_arg0Profesor.setContrasena("Contrasena370167851");
        _getSociosByClase_arg0Profesor.setEmail("Email-65710621");
        publicadores.LocalDate _getSociosByClase_arg0ProfesorFechaNac = new publicadores.LocalDate();
        _getSociosByClase_arg0Profesor.setFechaNac(_getSociosByClase_arg0ProfesorFechaNac);
        _getSociosByClase_arg0Profesor.setImg("Img1034975072");
        _getSociosByClase_arg0Profesor.setNickname("Nickname1000667197");
        _getSociosByClase_arg0Profesor.setNombre("Nombre-776348253");
        _getSociosByClase_arg0Profesor.setBiografia("Biografia1561415998");
        _getSociosByClase_arg0Profesor.setDescripcion("Descripcion1251003230");
        publicadores.InstitucionDeportiva _getSociosByClase_arg0ProfesorInstitucion = new publicadores.InstitucionDeportiva();
        java.util.List<publicadores.ActividadDeportiva> _getSociosByClase_arg0ProfesorInstitucionActividades = new java.util.ArrayList<publicadores.ActividadDeportiva>();
        _getSociosByClase_arg0ProfesorInstitucion.getActividades().addAll(_getSociosByClase_arg0ProfesorInstitucionActividades);
        _getSociosByClase_arg0ProfesorInstitucion.setDescripcion("Descripcion51855430");
        _getSociosByClase_arg0ProfesorInstitucion.setNombre("Nombre-409565357");
        _getSociosByClase_arg0ProfesorInstitucion.setUrl("Url-1186536491");
        _getSociosByClase_arg0Profesor.setInstitucion(_getSociosByClase_arg0ProfesorInstitucion);
        _getSociosByClase_arg0Profesor.setSitioWeb("SitioWeb2112204302");
        _getSociosByClase_arg0.setProfesor(_getSociosByClase_arg0Profesor);
        java.util.List<publicadores.Registro> _getSociosByClase_arg0Registros = new java.util.ArrayList<publicadores.Registro>();
        publicadores.Registro _getSociosByClase_arg0RegistrosVal1 = new publicadores.Registro();
        publicadores.Clase _getSociosByClase_arg0RegistrosVal1Clase = new publicadores.Clase();
        publicadores.LocalDate _getSociosByClase_arg0RegistrosVal1ClaseFecha = new publicadores.LocalDate();
        _getSociosByClase_arg0RegistrosVal1Clase.setFecha(_getSociosByClase_arg0RegistrosVal1ClaseFecha);
        publicadores.LocalDate _getSociosByClase_arg0RegistrosVal1ClaseFechaReg = new publicadores.LocalDate();
        _getSociosByClase_arg0RegistrosVal1Clase.setFechaReg(_getSociosByClase_arg0RegistrosVal1ClaseFechaReg);
        publicadores.LocalTime _getSociosByClase_arg0RegistrosVal1ClaseHora = new publicadores.LocalTime();
        _getSociosByClase_arg0RegistrosVal1Clase.setHora(_getSociosByClase_arg0RegistrosVal1ClaseHora);
        _getSociosByClase_arg0RegistrosVal1Clase.setImg("Img463727242");
        _getSociosByClase_arg0RegistrosVal1Clase.setNombre("Nombre-935834708");
        publicadores.Profesor _getSociosByClase_arg0RegistrosVal1ClaseProfesor = new publicadores.Profesor();
        _getSociosByClase_arg0RegistrosVal1ClaseProfesor.setApellido("Apellido-786641555");
        _getSociosByClase_arg0RegistrosVal1ClaseProfesor.setContrasena("Contrasena1793489272");
        _getSociosByClase_arg0RegistrosVal1ClaseProfesor.setEmail("Email103070933");
        publicadores.LocalDate _getSociosByClase_arg0RegistrosVal1ClaseProfesorFechaNac = new publicadores.LocalDate();
        _getSociosByClase_arg0RegistrosVal1ClaseProfesor.setFechaNac(_getSociosByClase_arg0RegistrosVal1ClaseProfesorFechaNac);
        _getSociosByClase_arg0RegistrosVal1ClaseProfesor.setImg("Img-1971789075");
        _getSociosByClase_arg0RegistrosVal1ClaseProfesor.setNickname("Nickname-1939693979");
        _getSociosByClase_arg0RegistrosVal1ClaseProfesor.setNombre("Nombre-2041601512");
        _getSociosByClase_arg0RegistrosVal1ClaseProfesor.setBiografia("Biografia1368338929");
        _getSociosByClase_arg0RegistrosVal1ClaseProfesor.setDescripcion("Descripcion-1603638913");
        publicadores.InstitucionDeportiva _getSociosByClase_arg0RegistrosVal1ClaseProfesorInstitucion = new publicadores.InstitucionDeportiva();
        java.util.List<publicadores.ActividadDeportiva> _getSociosByClase_arg0RegistrosVal1ClaseProfesorInstitucionActividades = new java.util.ArrayList<publicadores.ActividadDeportiva>();
        _getSociosByClase_arg0RegistrosVal1ClaseProfesorInstitucion.getActividades().addAll(_getSociosByClase_arg0RegistrosVal1ClaseProfesorInstitucionActividades);
        _getSociosByClase_arg0RegistrosVal1ClaseProfesorInstitucion.setDescripcion("Descripcion168762447");
        _getSociosByClase_arg0RegistrosVal1ClaseProfesorInstitucion.setNombre("Nombre-113212957");
        _getSociosByClase_arg0RegistrosVal1ClaseProfesorInstitucion.setUrl("Url1199145564");
        _getSociosByClase_arg0RegistrosVal1ClaseProfesor.setInstitucion(_getSociosByClase_arg0RegistrosVal1ClaseProfesorInstitucion);
        _getSociosByClase_arg0RegistrosVal1ClaseProfesor.setSitioWeb("SitioWeb-272773983");
        _getSociosByClase_arg0RegistrosVal1Clase.setProfesor(_getSociosByClase_arg0RegistrosVal1ClaseProfesor);
        java.util.List<publicadores.Registro> _getSociosByClase_arg0RegistrosVal1ClaseRegistros = new java.util.ArrayList<publicadores.Registro>();
        _getSociosByClase_arg0RegistrosVal1Clase.getRegistros().addAll(_getSociosByClase_arg0RegistrosVal1ClaseRegistros);
        _getSociosByClase_arg0RegistrosVal1Clase.setUrl("Url1755831233");
        _getSociosByClase_arg0RegistrosVal1.setClase(_getSociosByClase_arg0RegistrosVal1Clase);
        publicadores.LocalDate _getSociosByClase_arg0RegistrosVal1FechaReg = new publicadores.LocalDate();
        _getSociosByClase_arg0RegistrosVal1.setFechaReg(_getSociosByClase_arg0RegistrosVal1FechaReg);
        publicadores.Socio _getSociosByClase_arg0RegistrosVal1Socio = new publicadores.Socio();
        _getSociosByClase_arg0RegistrosVal1Socio.setApellido("Apellido-1325641849");
        _getSociosByClase_arg0RegistrosVal1Socio.setContrasena("Contrasena-367328197");
        _getSociosByClase_arg0RegistrosVal1Socio.setEmail("Email1527831879");
        publicadores.LocalDate _getSociosByClase_arg0RegistrosVal1SocioFechaNac = new publicadores.LocalDate();
        _getSociosByClase_arg0RegistrosVal1Socio.setFechaNac(_getSociosByClase_arg0RegistrosVal1SocioFechaNac);
        _getSociosByClase_arg0RegistrosVal1Socio.setImg("Img-2086132883");
        _getSociosByClase_arg0RegistrosVal1Socio.setNickname("Nickname573359607");
        _getSociosByClase_arg0RegistrosVal1Socio.setNombre("Nombre-539093362");
        java.util.List<publicadores.Registro> _getSociosByClase_arg0RegistrosVal1SocioClasesRegistradas = new java.util.ArrayList<publicadores.Registro>();
        _getSociosByClase_arg0RegistrosVal1Socio.getClasesRegistradas().addAll(_getSociosByClase_arg0RegistrosVal1SocioClasesRegistradas);
        _getSociosByClase_arg0RegistrosVal1.setSocio(_getSociosByClase_arg0RegistrosVal1Socio);
        _getSociosByClase_arg0Registros.add(_getSociosByClase_arg0RegistrosVal1);
        _getSociosByClase_arg0.getRegistros().addAll(_getSociosByClase_arg0Registros);
        _getSociosByClase_arg0.setUrl("Url340798783");
        publicadores.ArrayList _getSociosByClase__return = port.getSociosByClase(_getSociosByClase_arg0);
        System.out.println("getSociosByClase.result=" + _getSociosByClase__return);


        }
        {
        System.out.println("Invoking getClasesByUser...");
        java.lang.String _getClasesByUser_arg0 = "_getClasesByUser_arg0151678063";
        publicadores.ArrayList _getClasesByUser__return = port.getClasesByUser(_getClasesByUser_arg0);
        System.out.println("getClasesByUser.result=" + _getClasesByUser__return);


        }
        {
        System.out.println("Invoking getClasesByActividad...");
        java.lang.String _getClasesByActividad_arg0 = "_getClasesByActividad_arg0589905958";
        publicadores.ArrayList _getClasesByActividad__return = port.getClasesByActividad(_getClasesByActividad_arg0);
        System.out.println("getClasesByActividad.result=" + _getClasesByActividad__return);


        }
        {
        System.out.println("Invoking validateDataWeb...");
        java.lang.String _validateDataWeb_arg0 = "_validateDataWeb_arg0-683078747";
        java.lang.String _validateDataWeb_arg1 = "_validateDataWeb_arg1611785366";
        boolean _validateDataWeb__return = port.validateDataWeb(_validateDataWeb_arg0, _validateDataWeb_arg1);
        System.out.println("validateDataWeb.result=" + _validateDataWeb__return);


        }
        {
        System.out.println("Invoking obtenerActividadPorNombre...");
        java.lang.String _obtenerActividadPorNombre_arg0 = "_obtenerActividadPorNombre_arg0142152678";
        publicadores.ActividadDeportiva _obtenerActividadPorNombre__return = port.obtenerActividadPorNombre(_obtenerActividadPorNombre_arg0);
        System.out.println("obtenerActividadPorNombre.result=" + _obtenerActividadPorNombre__return);


        }
        {
        System.out.println("Invoking obtenerClasesPorActividad...");
        publicadores.ActividadDeportiva _obtenerClasesPorActividad_arg0 = new publicadores.ActividadDeportiva();
        _obtenerClasesPorActividad_arg0.setCosto(0.6862381f);
        _obtenerClasesPorActividad_arg0.setDescripcion("Descripcion-798570797");
        _obtenerClasesPorActividad_arg0.setDuracion(616213817);
        publicadores.LocalDate _obtenerClasesPorActividad_arg0FechaReg = new publicadores.LocalDate();
        _obtenerClasesPorActividad_arg0.setFechaReg(_obtenerClasesPorActividad_arg0FechaReg);
        _obtenerClasesPorActividad_arg0.setImg("Img-656404027");
        _obtenerClasesPorActividad_arg0.setNombre("Nombre-174718973");
        publicadores.ArrayList _obtenerClasesPorActividad__return = port.obtenerClasesPorActividad(_obtenerClasesPorActividad_arg0);
        System.out.println("obtenerClasesPorActividad.result=" + _obtenerClasesPorActividad__return);


        }
        {
        System.out.println("Invoking obtenerRankingDeActividades...");
        publicadores.ArrayList _obtenerRankingDeActividades__return = port.obtenerRankingDeActividades();
        System.out.println("obtenerRankingDeActividades.result=" + _obtenerRankingDeActividades__return);


        }
        {
        System.out.println("Invoking addClase...");
        java.lang.String _addClase_arg0 = "_addClase_arg0-1775304352";
        publicadores.LocalDate _addClase_arg1 = new publicadores.LocalDate();
        publicadores.LocalTime _addClase_arg2 = new publicadores.LocalTime();
        java.lang.String _addClase_arg3 = "_addClase_arg3-959304994";
        publicadores.LocalDate _addClase_arg4 = new publicadores.LocalDate();
        java.lang.String _addClase_arg5 = "_addClase_arg51650641131";
        java.lang.String _addClase_arg6 = "_addClase_arg6-705855212";
        java.lang.String _addClase_arg7 = "_addClase_arg7-973509949";
        port.addClase(_addClase_arg0, _addClase_arg1, _addClase_arg2, _addClase_arg3, _addClase_arg4, _addClase_arg5, _addClase_arg6, _addClase_arg7);


        }
        {
        System.out.println("Invoking getClaseByNombre...");
        java.lang.String _getClaseByNombre_arg0 = "_getClaseByNombre_arg0937067812";
        publicadores.Clase _getClaseByNombre__return = port.getClaseByNombre(_getClaseByNombre_arg0);
        System.out.println("getClaseByNombre.result=" + _getClaseByNombre__return);


        }
        {
        System.out.println("Invoking crearRegistro...");
        publicadores.Socio _crearRegistro_arg0 = new publicadores.Socio();
        _crearRegistro_arg0.setApellido("Apellido1331053680");
        _crearRegistro_arg0.setContrasena("Contrasena-201285134");
        _crearRegistro_arg0.setEmail("Email-1140451312");
        publicadores.LocalDate _crearRegistro_arg0FechaNac = new publicadores.LocalDate();
        _crearRegistro_arg0.setFechaNac(_crearRegistro_arg0FechaNac);
        _crearRegistro_arg0.setImg("Img-1048574472");
        _crearRegistro_arg0.setNickname("Nickname-1072597439");
        _crearRegistro_arg0.setNombre("Nombre1706195683");
        java.util.List<publicadores.Registro> _crearRegistro_arg0ClasesRegistradas = new java.util.ArrayList<publicadores.Registro>();
        publicadores.Registro _crearRegistro_arg0ClasesRegistradasVal1 = new publicadores.Registro();
        publicadores.Clase _crearRegistro_arg0ClasesRegistradasVal1Clase = new publicadores.Clase();
        publicadores.LocalDate _crearRegistro_arg0ClasesRegistradasVal1ClaseFecha = new publicadores.LocalDate();
        _crearRegistro_arg0ClasesRegistradasVal1Clase.setFecha(_crearRegistro_arg0ClasesRegistradasVal1ClaseFecha);
        publicadores.LocalDate _crearRegistro_arg0ClasesRegistradasVal1ClaseFechaReg = new publicadores.LocalDate();
        _crearRegistro_arg0ClasesRegistradasVal1Clase.setFechaReg(_crearRegistro_arg0ClasesRegistradasVal1ClaseFechaReg);
        publicadores.LocalTime _crearRegistro_arg0ClasesRegistradasVal1ClaseHora = new publicadores.LocalTime();
        _crearRegistro_arg0ClasesRegistradasVal1Clase.setHora(_crearRegistro_arg0ClasesRegistradasVal1ClaseHora);
        _crearRegistro_arg0ClasesRegistradasVal1Clase.setImg("Img-36112721");
        _crearRegistro_arg0ClasesRegistradasVal1Clase.setNombre("Nombre300670523");
        publicadores.Profesor _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesor = new publicadores.Profesor();
        _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesor.setApellido("Apellido275401454");
        _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesor.setContrasena("Contrasena1224627210");
        _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesor.setEmail("Email-1664272818");
        publicadores.LocalDate _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesorFechaNac = new publicadores.LocalDate();
        _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesor.setFechaNac(_crearRegistro_arg0ClasesRegistradasVal1ClaseProfesorFechaNac);
        _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesor.setImg("Img-357991775");
        _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesor.setNickname("Nickname1406117570");
        _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesor.setNombre("Nombre-1697095960");
        _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesor.setBiografia("Biografia404807192");
        _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesor.setDescripcion("Descripcion1804714716");
        publicadores.InstitucionDeportiva _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesorInstitucion = new publicadores.InstitucionDeportiva();
        java.util.List<publicadores.ActividadDeportiva> _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesorInstitucionActividades = new java.util.ArrayList<publicadores.ActividadDeportiva>();
        _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesorInstitucion.getActividades().addAll(_crearRegistro_arg0ClasesRegistradasVal1ClaseProfesorInstitucionActividades);
        _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesorInstitucion.setDescripcion("Descripcion56467475");
        _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesorInstitucion.setNombre("Nombre530711590");
        _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesorInstitucion.setUrl("Url2097676582");
        _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesor.setInstitucion(_crearRegistro_arg0ClasesRegistradasVal1ClaseProfesorInstitucion);
        _crearRegistro_arg0ClasesRegistradasVal1ClaseProfesor.setSitioWeb("SitioWeb-284645640");
        _crearRegistro_arg0ClasesRegistradasVal1Clase.setProfesor(_crearRegistro_arg0ClasesRegistradasVal1ClaseProfesor);
        java.util.List<publicadores.Registro> _crearRegistro_arg0ClasesRegistradasVal1ClaseRegistros = new java.util.ArrayList<publicadores.Registro>();
        _crearRegistro_arg0ClasesRegistradasVal1Clase.getRegistros().addAll(_crearRegistro_arg0ClasesRegistradasVal1ClaseRegistros);
        _crearRegistro_arg0ClasesRegistradasVal1Clase.setUrl("Url558533340");
        _crearRegistro_arg0ClasesRegistradasVal1.setClase(_crearRegistro_arg0ClasesRegistradasVal1Clase);
        publicadores.LocalDate _crearRegistro_arg0ClasesRegistradasVal1FechaReg = new publicadores.LocalDate();
        _crearRegistro_arg0ClasesRegistradasVal1.setFechaReg(_crearRegistro_arg0ClasesRegistradasVal1FechaReg);
        publicadores.Socio _crearRegistro_arg0ClasesRegistradasVal1Socio = new publicadores.Socio();
        _crearRegistro_arg0ClasesRegistradasVal1Socio.setApellido("Apellido1970194833");
        _crearRegistro_arg0ClasesRegistradasVal1Socio.setContrasena("Contrasena-1738914251");
        _crearRegistro_arg0ClasesRegistradasVal1Socio.setEmail("Email1253809928");
        publicadores.LocalDate _crearRegistro_arg0ClasesRegistradasVal1SocioFechaNac = new publicadores.LocalDate();
        _crearRegistro_arg0ClasesRegistradasVal1Socio.setFechaNac(_crearRegistro_arg0ClasesRegistradasVal1SocioFechaNac);
        _crearRegistro_arg0ClasesRegistradasVal1Socio.setImg("Img-740251256");
        _crearRegistro_arg0ClasesRegistradasVal1Socio.setNickname("Nickname1084429413");
        _crearRegistro_arg0ClasesRegistradasVal1Socio.setNombre("Nombre-1486571878");
        java.util.List<publicadores.Registro> _crearRegistro_arg0ClasesRegistradasVal1SocioClasesRegistradas = new java.util.ArrayList<publicadores.Registro>();
        _crearRegistro_arg0ClasesRegistradasVal1Socio.getClasesRegistradas().addAll(_crearRegistro_arg0ClasesRegistradasVal1SocioClasesRegistradas);
        _crearRegistro_arg0ClasesRegistradasVal1.setSocio(_crearRegistro_arg0ClasesRegistradasVal1Socio);
        _crearRegistro_arg0ClasesRegistradas.add(_crearRegistro_arg0ClasesRegistradasVal1);
        _crearRegistro_arg0.getClasesRegistradas().addAll(_crearRegistro_arg0ClasesRegistradas);
        publicadores.Clase _crearRegistro_arg1 = new publicadores.Clase();
        publicadores.LocalDate _crearRegistro_arg1Fecha = new publicadores.LocalDate();
        _crearRegistro_arg1.setFecha(_crearRegistro_arg1Fecha);
        publicadores.LocalDate _crearRegistro_arg1FechaReg = new publicadores.LocalDate();
        _crearRegistro_arg1.setFechaReg(_crearRegistro_arg1FechaReg);
        publicadores.LocalTime _crearRegistro_arg1Hora = new publicadores.LocalTime();
        _crearRegistro_arg1.setHora(_crearRegistro_arg1Hora);
        _crearRegistro_arg1.setImg("Img-103415550");
        _crearRegistro_arg1.setNombre("Nombre1226938128");
        publicadores.Profesor _crearRegistro_arg1Profesor = new publicadores.Profesor();
        _crearRegistro_arg1Profesor.setApellido("Apellido205933517");
        _crearRegistro_arg1Profesor.setContrasena("Contrasena-275445646");
        _crearRegistro_arg1Profesor.setEmail("Email361386215");
        publicadores.LocalDate _crearRegistro_arg1ProfesorFechaNac = new publicadores.LocalDate();
        _crearRegistro_arg1Profesor.setFechaNac(_crearRegistro_arg1ProfesorFechaNac);
        _crearRegistro_arg1Profesor.setImg("Img7192135");
        _crearRegistro_arg1Profesor.setNickname("Nickname-185196630");
        _crearRegistro_arg1Profesor.setNombre("Nombre1314052125");
        _crearRegistro_arg1Profesor.setBiografia("Biografia1293807399");
        _crearRegistro_arg1Profesor.setDescripcion("Descripcion1650160244");
        publicadores.InstitucionDeportiva _crearRegistro_arg1ProfesorInstitucion = new publicadores.InstitucionDeportiva();
        java.util.List<publicadores.ActividadDeportiva> _crearRegistro_arg1ProfesorInstitucionActividades = new java.util.ArrayList<publicadores.ActividadDeportiva>();
        _crearRegistro_arg1ProfesorInstitucion.getActividades().addAll(_crearRegistro_arg1ProfesorInstitucionActividades);
        _crearRegistro_arg1ProfesorInstitucion.setDescripcion("Descripcion-1878984813");
        _crearRegistro_arg1ProfesorInstitucion.setNombre("Nombre783189228");
        _crearRegistro_arg1ProfesorInstitucion.setUrl("Url697747778");
        _crearRegistro_arg1Profesor.setInstitucion(_crearRegistro_arg1ProfesorInstitucion);
        _crearRegistro_arg1Profesor.setSitioWeb("SitioWeb-1383170783");
        _crearRegistro_arg1.setProfesor(_crearRegistro_arg1Profesor);
        java.util.List<publicadores.Registro> _crearRegistro_arg1Registros = new java.util.ArrayList<publicadores.Registro>();
        publicadores.Registro _crearRegistro_arg1RegistrosVal1 = new publicadores.Registro();
        publicadores.Clase _crearRegistro_arg1RegistrosVal1Clase = new publicadores.Clase();
        publicadores.LocalDate _crearRegistro_arg1RegistrosVal1ClaseFecha = new publicadores.LocalDate();
        _crearRegistro_arg1RegistrosVal1Clase.setFecha(_crearRegistro_arg1RegistrosVal1ClaseFecha);
        publicadores.LocalDate _crearRegistro_arg1RegistrosVal1ClaseFechaReg = new publicadores.LocalDate();
        _crearRegistro_arg1RegistrosVal1Clase.setFechaReg(_crearRegistro_arg1RegistrosVal1ClaseFechaReg);
        publicadores.LocalTime _crearRegistro_arg1RegistrosVal1ClaseHora = new publicadores.LocalTime();
        _crearRegistro_arg1RegistrosVal1Clase.setHora(_crearRegistro_arg1RegistrosVal1ClaseHora);
        _crearRegistro_arg1RegistrosVal1Clase.setImg("Img67751452");
        _crearRegistro_arg1RegistrosVal1Clase.setNombre("Nombre1490330904");
        publicadores.Profesor _crearRegistro_arg1RegistrosVal1ClaseProfesor = new publicadores.Profesor();
        _crearRegistro_arg1RegistrosVal1ClaseProfesor.setApellido("Apellido-1727991630");
        _crearRegistro_arg1RegistrosVal1ClaseProfesor.setContrasena("Contrasena-1692781262");
        _crearRegistro_arg1RegistrosVal1ClaseProfesor.setEmail("Email-973603749");
        publicadores.LocalDate _crearRegistro_arg1RegistrosVal1ClaseProfesorFechaNac = new publicadores.LocalDate();
        _crearRegistro_arg1RegistrosVal1ClaseProfesor.setFechaNac(_crearRegistro_arg1RegistrosVal1ClaseProfesorFechaNac);
        _crearRegistro_arg1RegistrosVal1ClaseProfesor.setImg("Img-357546763");
        _crearRegistro_arg1RegistrosVal1ClaseProfesor.setNickname("Nickname-331596793");
        _crearRegistro_arg1RegistrosVal1ClaseProfesor.setNombre("Nombre-217746632");
        _crearRegistro_arg1RegistrosVal1ClaseProfesor.setBiografia("Biografia2014951847");
        _crearRegistro_arg1RegistrosVal1ClaseProfesor.setDescripcion("Descripcion420832616");
        publicadores.InstitucionDeportiva _crearRegistro_arg1RegistrosVal1ClaseProfesorInstitucion = new publicadores.InstitucionDeportiva();
        java.util.List<publicadores.ActividadDeportiva> _crearRegistro_arg1RegistrosVal1ClaseProfesorInstitucionActividades = new java.util.ArrayList<publicadores.ActividadDeportiva>();
        _crearRegistro_arg1RegistrosVal1ClaseProfesorInstitucion.getActividades().addAll(_crearRegistro_arg1RegistrosVal1ClaseProfesorInstitucionActividades);
        _crearRegistro_arg1RegistrosVal1ClaseProfesorInstitucion.setDescripcion("Descripcion1856001620");
        _crearRegistro_arg1RegistrosVal1ClaseProfesorInstitucion.setNombre("Nombre1797846791");
        _crearRegistro_arg1RegistrosVal1ClaseProfesorInstitucion.setUrl("Url-1702341725");
        _crearRegistro_arg1RegistrosVal1ClaseProfesor.setInstitucion(_crearRegistro_arg1RegistrosVal1ClaseProfesorInstitucion);
        _crearRegistro_arg1RegistrosVal1ClaseProfesor.setSitioWeb("SitioWeb1886416278");
        _crearRegistro_arg1RegistrosVal1Clase.setProfesor(_crearRegistro_arg1RegistrosVal1ClaseProfesor);
        java.util.List<publicadores.Registro> _crearRegistro_arg1RegistrosVal1ClaseRegistros = new java.util.ArrayList<publicadores.Registro>();
        _crearRegistro_arg1RegistrosVal1Clase.getRegistros().addAll(_crearRegistro_arg1RegistrosVal1ClaseRegistros);
        _crearRegistro_arg1RegistrosVal1Clase.setUrl("Url2059919561");
        _crearRegistro_arg1RegistrosVal1.setClase(_crearRegistro_arg1RegistrosVal1Clase);
        publicadores.LocalDate _crearRegistro_arg1RegistrosVal1FechaReg = new publicadores.LocalDate();
        _crearRegistro_arg1RegistrosVal1.setFechaReg(_crearRegistro_arg1RegistrosVal1FechaReg);
        publicadores.Socio _crearRegistro_arg1RegistrosVal1Socio = new publicadores.Socio();
        _crearRegistro_arg1RegistrosVal1Socio.setApellido("Apellido1024856709");
        _crearRegistro_arg1RegistrosVal1Socio.setContrasena("Contrasena-280403334");
        _crearRegistro_arg1RegistrosVal1Socio.setEmail("Email1921942494");
        publicadores.LocalDate _crearRegistro_arg1RegistrosVal1SocioFechaNac = new publicadores.LocalDate();
        _crearRegistro_arg1RegistrosVal1Socio.setFechaNac(_crearRegistro_arg1RegistrosVal1SocioFechaNac);
        _crearRegistro_arg1RegistrosVal1Socio.setImg("Img1102678689");
        _crearRegistro_arg1RegistrosVal1Socio.setNickname("Nickname-1673744956");
        _crearRegistro_arg1RegistrosVal1Socio.setNombre("Nombre177765739");
        java.util.List<publicadores.Registro> _crearRegistro_arg1RegistrosVal1SocioClasesRegistradas = new java.util.ArrayList<publicadores.Registro>();
        _crearRegistro_arg1RegistrosVal1Socio.getClasesRegistradas().addAll(_crearRegistro_arg1RegistrosVal1SocioClasesRegistradas);
        _crearRegistro_arg1RegistrosVal1.setSocio(_crearRegistro_arg1RegistrosVal1Socio);
        _crearRegistro_arg1Registros.add(_crearRegistro_arg1RegistrosVal1);
        _crearRegistro_arg1.getRegistros().addAll(_crearRegistro_arg1Registros);
        _crearRegistro_arg1.setUrl("Url534643208");
        boolean _crearRegistro__return = port.crearRegistro(_crearRegistro_arg0, _crearRegistro_arg1);
        System.out.println("crearRegistro.result=" + _crearRegistro__return);


        }
        {
        System.out.println("Invoking obtenerClasePorNombre...");
        java.lang.String _obtenerClasePorNombre_arg0 = "_obtenerClasePorNombre_arg01538278206";
        publicadores.Clase _obtenerClasePorNombre__return = port.obtenerClasePorNombre(_obtenerClasePorNombre_arg0);
        System.out.println("obtenerClasePorNombre.result=" + _obtenerClasePorNombre__return);


        }
        {
        System.out.println("Invoking iniciarSesion...");
        java.lang.String _iniciarSesion_arg0 = "_iniciarSesion_arg0-1453000621";
        java.lang.String _iniciarSesion_arg1 = "_iniciarSesion_arg1-1535560825";
        publicadores.Sesion _iniciarSesion__return = port.iniciarSesion(_iniciarSesion_arg0, _iniciarSesion_arg1);
        System.out.println("iniciarSesion.result=" + _iniciarSesion__return);


        }
        {
        System.out.println("Invoking getInstitucionesByName...");
        java.lang.String _getInstitucionesByName_arg0 = "_getInstitucionesByName_arg0616921278";
        publicadores.InstitucionDeportiva _getInstitucionesByName__return = port.getInstitucionesByName(_getInstitucionesByName_arg0);
        System.out.println("getInstitucionesByName.result=" + _getInstitucionesByName__return);


        }
        {
        System.out.println("Invoking getActividadesByProfe...");
        java.lang.String _getActividadesByProfe_arg0 = "_getActividadesByProfe_arg0171043473";
        publicadores.ArrayList _getActividadesByProfe__return = port.getActividadesByProfe(_getActividadesByProfe_arg0);
        System.out.println("getActividadesByProfe.result=" + _getActividadesByProfe__return);


        }
        {
        System.out.println("Invoking addRegistroDictadoWeb...");
        java.lang.String _addRegistroDictadoWeb_arg0 = "_addRegistroDictadoWeb_arg01292000209";
        java.lang.String _addRegistroDictadoWeb_arg1 = "_addRegistroDictadoWeb_arg1208227513";
        publicadores.LocalDate _addRegistroDictadoWeb_arg2 = new publicadores.LocalDate();
        boolean _addRegistroDictadoWeb__return = port.addRegistroDictadoWeb(_addRegistroDictadoWeb_arg0, _addRegistroDictadoWeb_arg1, _addRegistroDictadoWeb_arg2);
        System.out.println("addRegistroDictadoWeb.result=" + _addRegistroDictadoWeb__return);


        }
        {
        System.out.println("Invoking obtenerRankingDeClases...");
        publicadores.ArrayList _obtenerRankingDeClases__return = port.obtenerRankingDeClases();
        System.out.println("obtenerRankingDeClases.result=" + _obtenerRankingDeClases__return);


        }
        {
        System.out.println("Invoking getInstituciones...");
        publicadores.ArrayList _getInstituciones__return = port.getInstituciones();
        System.out.println("getInstituciones.result=" + _getInstituciones__return);


        }
        {
        System.out.println("Invoking getSocio...");
        java.lang.String _getSocio_arg0 = "_getSocio_arg0-1432160710";
        publicadores.Socio _getSocio__return = port.getSocio(_getSocio_arg0);
        System.out.println("getSocio.result=" + _getSocio__return);


        }
        {
        System.out.println("Invoking eliminarRegistroDeClase...");
        java.lang.String _eliminarRegistroDeClase_arg0 = "_eliminarRegistroDeClase_arg0-734649409";
        java.lang.String _eliminarRegistroDeClase_arg1 = "_eliminarRegistroDeClase_arg1-64322622";
        java.lang.String _eliminarRegistroDeClase_arg2 = "_eliminarRegistroDeClase_arg2117937927";
        java.lang.String _eliminarRegistroDeClase_arg3 = "_eliminarRegistroDeClase_arg3-957578176";
        boolean _eliminarRegistroDeClase__return = port.eliminarRegistroDeClase(_eliminarRegistroDeClase_arg0, _eliminarRegistroDeClase_arg1, _eliminarRegistroDeClase_arg2, _eliminarRegistroDeClase_arg3);
        System.out.println("eliminarRegistroDeClase.result=" + _eliminarRegistroDeClase__return);


        }

        System.exit(0);
    }

}
